/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTriangle */

#ifndef _Included_JTriangle
#define _Included_JTriangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JTriangle
 * Method:    printFlags
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JTriangle_printFlags
  (JNIEnv *, jclass);

/*
 * Class:     JTriangle
 * Method:    triangulateV1
 * Signature: ([F)[I
 */
JNIEXPORT jintArray JNICALL Java_JTriangle_triangulateV1
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     JTriangle
 * Method:    triangulate
 * Signature: (Ljava/lang/String;LTriangulateIO;LTriangulateIO;LTriangulateIO;)V
 */
JNIEXPORT void JNICALL Java_JTriangle_triangulate
  (JNIEnv *, jclass, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
