/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTriangle */

#ifndef _Included_JTriangle
#define _Included_JTriangle
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_dedovic_jtriangle_triangle_JTriangle
* Method:    triangulateInternal
* Signature: (Ljava/lang/String;Lcom/dedovic/jtriangle/triangle/TriangulateIO;Lcom/dedovic/jtriangle/triangle/TriangulateIO;Lcom/dedovic/jtriangle/triangle/TriangulateIO;)V
*/
JNIEXPORT void JNICALL Java_com_dedovic_jtriangle_triangle_JTriangle_triangulateInternal
        (JNIEnv *, jclass, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
