/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JTriangle */

#ifndef _Included_JTriangle
#define _Included_JTriangle
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     JTriangle
 * Method:    printFlags
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JTriangle_printFlags
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
